---
title: "Changement d’heure : les données ont leur mot à dire"
subtitle: "Une datavisualisation maison pour donner vie aux résultats"

author: gmo
format:
  html:
    echo: false
    code-tools: false
    embed-resources: true
    
    
    include-in-header: 
      text: |
        <style>
          p {
            text-align: left;
          }
        </style>

---

Pour ceux qui me connaissent, ils savent que j’aime manipuler les données. Et aujourd’hui, on peut en trouver beaucoup sur des sujets très variés, comme par exemple le changement d’heure été/hiver.

Du 4 février au 3 mars 2019, la Commission des affaires européennes en France a lancé une <a href="https://data.assemblee-nationale.fr/autres/consultations-citoyennes/changement-d-heure">consultation citoyenne sur le changement d’heure </a>. Cette consultation a recueilli <b>2 103 999 réponses</b>.

Sur le site, on trouve un lien vers les données au format SQL ainsi qu’un bref résumé des résultats, mais sans visualisation des données — ce qui est un peu dommage.

Je vous passe tous les aspects techniques, mais ci-dessous se trouve la dataviz <b>interactive</b> que j’ai réalisée, et qui, selon moi, résume bien les résultats.

Sans surprise, vous pouvez constater que pour la majorité d’entre nous, quelle que soit la région, l’expérience du changement d’heure n’est pas bonne. En effet, plus de 50 % des personnes, dans toutes les régions, déclarent une expérience négative ou très négative du changement d’heure.

<i>Selectionner un(des) type(s) d'experience(s):</i>

```{ojs}

data = FileAttachment("data/Consultation_Chgt_Heure.csv").csv({ typed: true })

filtered_a = data.filter(function(product) {
                  return experience.includes(product.Name_Experience)
                  })


viewof experience = Inputs.checkbox(["Très satisfaisante","Satisfaisante","Sans opinion","Négative","Très négative"], {label: "", multiple:true, value: ["Très satisfaisante","Satisfaisante","Sans opinion","Négative","Très négative"]})

html`<br>`

Plot.plot({
  height: 600,
  marginLeft:150,

  x: {
      label: "%",
      grid: true
    },

  y: {
    domain: d3.sort(filtered_a, d => - (d.Total/d.Total_Region)).map(d => d.Name_Region),
    grid: true,
    },
 
 color: {legend: true}, 
 
 caption: "Expression de la satisfaction (en %) sur le changement d'heure par region",  
 
  marks: [
    Plot.barX(filtered_a,{
     y: l => l.Name_Region,
     x: d => d.Total / d.Total_Region * 100,
     fill: u => u.Name_Experience,
     tip: true
     }),
     
     Plot.ruleX([50], {stroke: "red", strokeWidth: 2})
     ]
})

```

En revanche, si vous sélectionnez uniquement les expériences extrêmes — très négatives — dans le graphique, on peut constater quelque chose d’étonnant dans les résultats : ce sont les régions d’outre-mer (DOM-TOM) qui ont exprimé le plus souvent une expérience très négative, comparativement aux régions métropolitaines.

L’explication est facile à trouver sur Internet : les habitants des DOM-TOM ne changent jamais d’heure en raison d’une faible variation de l’ensoleillement tout au long de l’année, liée à leur proximité avec l’équateur.

Cependant, le changement d’heure en France métropolitaine modifie le décalage horaire avec les DOM-TOM, ce qui peut perturber les appels professionnels, les visioconférences, ou encore les horaires de diffusion (journaux télévisés, matchs, etc.). Les habitants d’outre-mer doivent également anticiper les nouveaux horaires des services métropolitains. C’est pourquoi le changement d’heure est parfois perçu comme une mesure métropolitaine peu adaptée à leur quotidien — d’où les résultats de satisfaction très négatifs dans ces régions.

Comme quoi, les données ont toujours <b>une histoire à nous raconter…</b>



